### ISSUE TITLE
confusing repr

### ISSUE THREAD

**Issue by Akuli** [saskakarsi/trict#4]
There is no good way to figure out whether something is a `Trict` or a regular dictionary by just looking at it.

```python3
>>> t = trict.Trict({})
>>> t['a.b.c'] = 'd'
>>> t
{'a': {'b': {'c': 'd'}}}
>>> dict(t)
{'a': {'b': {'c': 'd'}}}
>>> 
```

I think typing `t` on the prompt should show something like `Trict({'a': {'b': {'c': 'd'}}})`. You can override `__repr__` for that, something like this:

```python3
def __repr__(self):
    return f'Trict({super().__repr__()})'
```

**Comment by saska** [comment]
Great catch, thank you. Will go with `f'{type(self).__name__}({super().__repr__()})'` to accomodate subclassing

**Comment by saska** [comment]
fbf9d4e74513c16ffd63f038d769815a0085c436

**Comment by Akuli** [comment]
Including `type(self).__name__` is even better than what I suggested, because now it does the right thing if someone wants to create their own subclass of `Trict`.
