### ISSUE TITLE
allow tuples and other iterables instead of just lists

### ISSUE THREAD

**Issue by Akuli** [saskakarsi/trict#5]
```python3
>>> t = trict.Trict({})
>>> t[('a', 'b', 'c')] = 'd'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/trict/trict/trict.py", line 55, in __setitem__
    key = self.key_to_list(key)
  File "/tmp/trict/trict/trict.py", line 76, in key_to_list
    raise TypeError('Key is not list or str')
TypeError: Key is not list or str
>>> 
```

I think `Trict` should check whether the key is a string (usually  `isinstance` is preferred over `type`), and if it's not a string, then **assume** that it behaves like a list. Most Python code is written that way, and works well with different kinds of iterables, not only lists.

**Comment by saska** [comment]
Great point, agree completely. Will implement

**Comment by saska** [comment]
d298e925b957a7c03287ed77a43f97afe3cee494
